-- AlterEnum
ALTER TYPE "RequestEventType" ADD VALUE 'ORDER_CONFIRMED';
ALTER TYPE "RequestEventType" ADD VALUE 'PRODUCTION_STARTED';
ALTER TYPE "RequestEventType" ADD VALUE 'ORDER_DISPATCHED';
ALTER TYPE "RequestEventType" ADD VALUE 'ORDER_DELIVERED';
